from flask import render_template, url_for, flash, redirect
from creator import app
from creator.forms import RegistrationForm, LoginForm
from creator.models import User, Post


# Secret key generated by using terminal. Enter Python > import secrets > secrets.token_hex(16)
app.config['SECRET_KEY'] = 'a483bfcafe108667ba2ea72c10084d07'

@app.route('/')
def home():
    return render_template('home.html')

@app.route("/about")
def about():
    return render_template('about.html', title='About Us')


#flask redirect and flash message currently not working. Will look into it later
@app.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('home'))
    return render_template('register.html', title='Register', form=form)


@app.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm
    return render_template('login.html', title = 'Login', form=form())
